### ISSUE TITLE
spine is not work well

### ISSUE THREAD

**Issue by indication** [indication/docker-cacti#1]
It shows following:

```
FATAL: Connection to Cacti database failed. Please ensure: 

  - the PHP MySQL module is installed and enabled.
  - the database is running.
  - the credentials in config.php are valid.

```

**Comment by indication** [comment]
It got segmentation fault.

```
/var/www/html/cacti # sudo -u www-data /usr/local/spine/bin/spine -C /etc/spine.conf 
SPINE: Using spine config file [/etc/spine.conf]
SPINE: Version 1.2.2 starting
Segmentation fault
```

**Comment by indication** [comment]
```
/var/www/html/cacti/spine # export CFLAGS=-g
/var/www/html/cacti/spine # make 
/var/www/html/cacti/spine # ./spine
SPINE: Using spine config file [/etc/spine.conf]
SPINE: Version 1.2.2 starting
Segmentation fault (core dumped)
/var/www/html/cacti/spine # gdb ./spine core.3508 
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./spine...done.
[New LWP 3509]
[New LWP 3508]

warning: Can't read pathname for load map: No error information.
Core was generated by `./spine'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  poll_host (host_id=host_id@entry=1, host_thread=host_thread@entry=1, last_host_thread=last_host_thread@entry=1, 
    host_data_ids=host_data_ids@entry=0, host_time=host_time@entry=0x7f4827e88960 "2019-03-07 15:33:15", 
    host_errors=host_errors@entry=0x7f4827e88958, host_time_double=<unavailable>, 
    host_time_double@entry=1551972795.383692) at poller.c:125
125     void poll_host(int host_id, int host_thread, int last_host_thread, int host_data_ids, char *host_time, int *host_errors, double host_time_double) {
[Current thread is 1 (LWP 3509)]
(gdb) bt
#0  poll_host (host_id=host_id@entry=1, host_thread=host_thread@entry=1, last_host_thread=last_host_thread@entry=1, 
    host_data_ids=host_data_ids@entry=0, host_time=host_time@entry=0x7f4827e88960 "2019-03-07 15:33:15", 
    host_errors=host_errors@entry=0x7f4827e88958, host_time_double=<unavailable>, 
    host_time_double@entry=1551972795.383692) at poller.c:125
#1  0x000055919a74f9c9 in child (arg=0x55919c141b60) at poller.c:79
#2  0x00007f4827c506c2 in ?? () from /lib/ld-musl-x86_64.so.1
#3  0x0000000000000000 in ?? ()
(gdb) quit
```

It may be lack of stack...

```
/var/www/html/cacti/spine # ulimit -a
-f: file size (blocks)             unlimited
-t: cpu time (seconds)             unlimited
-d: data seg size (kb)             unlimited
-s: stack size (kb)                10240
-c: core file size (blocks)        unlimited
-m: resident set size (kb)         unlimited
-l: locked memory (kb)             64
-p: processes                      unlimited
-n: file descriptors               1048576
-v: address space (kb)             unlimited
-w: locks                          unlimited
-e: scheduling priority            0
-r: real-time priority             0
```

It could not increace stacksize over 10MB. By default, 8MB.
